### ISSUE TITLE
Can't Run Gulp - 'Cannot Find Module genish.js'

### ISSUE THREAD

**Issue by bcgreen24** [charlieroberts/gibber.max#23]
When running 'gulp' or 'gulp build' from the gibberwocky root directory, I'm getting this error:

```
Error: Cannot find module 'genish.js' from 'C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\js'
    at C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\bcgre\gibberwocky-devel\gibberwocky-devel\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:171:21)
```

Node:
v13.13.0

Gulp:
CLI version: 2.2.0
Local version: 4.0.2

**Comment by charlieroberts** [comment]
The package.json is a bit of a mess, but https://github.com/gibber-cc/gibberwocky/commit/2013882e5f954f5732c805a892f23fcd9c0c0396 should at least fix this problem.
